#!/usr/bin/env python3
"""Render the synthetic public route map from the public registry fixture."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "architecture" / "examples" / "minimal-registry.json"
OUTPUT = ROOT / "architecture" / "examples" / "generated-route-map.md"


def render(registry: dict[str, object]) -> str:
    lines = [
        "# Generated synthetic route map",
        "",
        "<!-- Generated by scripts/render_route_maps.py. Edit architecture/examples/minimal-registry.json instead. -->",
        "",
        "This map is generated exclusively from the fictional public registry fixture. It is not a live route table, profile resolution, or private configuration export.",
        "",
    ]

    for router in registry["routers"]:
        lines.extend(
            [
                f"## {router['title']}",
                "",
                router["description"],
                "",
                "| Intent | Target | Side-effect class |",
                "| --- | --- | --- |",
            ]
        )
        for route in router["routes"]:
            lines.append(
                f"| {route['intent']} | `{route['target']}` | `{route['side_effect']}` |"
            )
        lines.append("")

    lines.extend(
        [
            "## Profiles in the fixture",
            "",
            "| Profile | Allowed ownership | Enabled skills |",
            "| --- | --- | --- |",
        ]
    )
    for profile in registry["profiles"]:
        owners = ", ".join(f"`{item}`" for item in profile["allowed_ownership"])
        skills = ", ".join(f"`{item}`" for item in profile["enabled_skills"])
        lines.append(f"| `{profile['id']}` | {owners} | {skills} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the generated map is stale.")
    args = parser.parse_args()

    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    rendered = render(registry)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print("ERROR: generated route map is stale; run scripts/render_route_maps.py", file=sys.stderr)
            return 1
        print("Generated synthetic route map is current.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Rendered {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
