#!/usr/bin/env python3
"""Render docs/skills.md from the canonical public artifact manifest."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "catalog" / "artifacts.json"
OUTPUT = ROOT / "docs" / "skills.md"
GROUPS = [
    ("current-snapshot", "Current public snapshots"),
    ("curated-projection", "Curated public projections"),
    ("illustrative-only", "Illustrative examples"),
    ("superseded", "Superseded standalone patterns"),
]


def escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render(manifest: dict[str, object]) -> str:
    artifacts = manifest["artifacts"]
    lines = [
        "# Public skill catalog",
        "",
        "<!-- Generated by scripts/render_public_catalog.py. Edit catalog/artifacts.json instead. -->",
        "",
        f"Last reviewed: {manifest['last_reviewed']}",
        "",
        "AI Workbench is a curated public collection, not a mirror of a maintainer's live agent environment. "
        "Every listed `SKILL.md` passes this repository's structural contract, but lifecycle and evidence differ by artifact.",
        "",
        "## Publication classes",
        "",
        "- **Current public snapshot:** maintained here as a usable public snapshot. It may still differ from private or newer variants.",
        "- **Curated public projection:** deliberately abstracted from a broader working pattern; public and live versions are not expected to match.",
        "- **Illustrative example:** useful for study or adaptation, without a live-parity claim.",
        "- **Superseded standalone pattern:** retained for historical or conceptual value; use the named successor direction for new architecture.",
        "",
    ]

    for class_name, heading in GROUPS:
        group = [item for item in artifacts if item["publication_class"] == class_name]
        lines.extend(
            [
                f"## {heading}",
                "",
                "| Skill | Public version | Relationship | Validation | Replacement or note |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for item in sorted(group, key=lambda entry: entry["title"].lower()):
            link = f"../{item['path']}/README.md"
            validation = ", ".join(item["validation"])
            final_column = item["replacement"] or item["notes"]
            lines.append(
                "| "
                f"[{escape(item['title'])}]({link}) | "
                f"{escape(item['public_version'])} | "
                f"{escape(item['source_relationship'])} | "
                f"{escape(validation)} | "
                f"{escape(final_column)} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Installation and adaptation",
            "",
            "For local Codex authoring, copy a selected skill into a repository or user `.agents/skills` directory. "
            "Other hosts may use a different skill location.",
            "",
            "Before installing:",
            "",
            "1. Check the publication class and last-reviewed date in `catalog/artifacts.json`.",
            "2. Read the skill's README, references, scripts, and side-effect boundaries.",
            "3. Adapt auth, tool, model, and MCP assumptions to current official documentation.",
            "4. Run the relevant validators or evals and preserve their stated claim limits.",
            "",
            "No plugin, release, compatibility guarantee, or automatic update channel is currently published from this repository.",
            "",
            "## Public boundary",
            "",
            "Public artifacts must not include raw live profiles, private skills, provider caches, credentials, account state, transcripts, "
            "memory stores, customer or employer context, or machine-specific paths. Drift detection may produce a review report; it must not auto-publish changes.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when docs/skills.md is stale")
    args = parser.parse_args()

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    rendered = render(manifest)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print("ERROR: docs/skills.md is stale; run scripts/render_public_catalog.py", file=sys.stderr)
            return 1
        print("Generated public skill catalog is current.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Rendered {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
